# Generated by Django 5.1.3 on 2025-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
