# Generated by Django 5.1.3 on 2025-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem', '0002_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
